[package]
name = "meloweb"
version = "0.1.0"
authors = ["Claire Harris <claire.harris.000@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
base64 = "~0.9.0"
melo = { path="../melo", default-features = false }
stdweb = "~0.4.0"

[patch.crates-io]
rimd = { path = "./rimd" }
